---
title: "Plotly"
author: "Rae Spriggs"
date: "2022-10-25"
output: html_document
        toc: true
        toc_float: true
---

## Load packages and data

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Let's get some data!
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, price, room_type, lat, long, rating) %>% 
  filter(
    borough == "Manhattan", 
    room_type == "Entire home/apt", 
    price %in% 100:500) %>% 
  drop_na(rating)

```

Let's make a scatterplot!
```{r}
nyc_airbnb %>%
  mutate(
    text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

Boxplots? 
```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y= ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

Can we make a bar plot? 

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  count(neighbourhood) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, 
    type = "bar"
  )
```
